### ISSUE TITLE
Bill title should be left aligned with all the boxes

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#100]
![image](https://user-images.githubusercontent.com/69854688/102823297-a6fb8400-43a8-11eb-90fd-a414f95af366.png)

Currently, that section and its text inside is centered aligned. Please left align according to the picture

**Comment by aih** [comment]
Current view:
![image](https://user-images.githubusercontent.com/217356/119236845-6edea580-baee-11eb-90d7-92914e1b9ae6.png)

Closing
