### ISSUE TITLE
Bill summary should be a small description instead of a "read bill" button

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#101]
![image](https://user-images.githubusercontent.com/69854688/102897849-a90c2400-4436-11eb-8687-cfd0870ffece.png)

** The demo presents a "read bill" button. Should have a small description instead.

**Comment by nkinaba** [comment]
1. The "Bill Summary" should include a short summary of the bill up to "x" amount of characters. Ellipses should reflect if the summary is longer than "x" amount of characters and a hover over action should allow the user to see the full summary.

 2. "Read Bill" button should be moved to the bottom of the overview section. When the user clicks on the "Read Bill" button, it should take them to a PDF of the full bill 

<img width="608" alt="Screen Shot 2020-12-28 at 4 13 28 PM" src="https://user-images.githubusercontent.com/69855502/103243360-a2464b00-4927-11eb-8b83-ddc46d9e4b3d.png">

**Comment by aih** [comment]
This is now text:
![image](https://user-images.githubusercontent.com/217356/110542718-45f96780-80de-11eb-9223-1b689e0bee71.png)

I'll open a separate issue to populate with the actual bill summary (currently is hardcoded text).
