### ISSUE TITLE
UI update for "Overview" section on the bill page

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#102]
**Current image of the "Overview" section**

<img width="570" alt="Screen Shot 2021-02-02 at 11 33 05 AM" src="https://user-images.githubusercontent.com/69855502/106631092-6b78db80-654a-11eb-9486-5e791975973c.png">

**The "Overview" section should look like the image below**

<img width="608" alt="Screen Shot 2020-12-28 at 4 20 05 PM" src="https://user-images.githubusercontent.com/69855502/103243657-8e4f1900-4928-11eb-90c9-03bb331eabb1.png">

**Bill Summary**
-The "Bill Summary" should include a short summary of the bill up to "x" amount of characters. Ellipses should reflect if the summary is longer than "x" amount of characters and a "see more" option that expands the container to show the entire summary of the bill

**Bill Stage**
-Current stage the bill is at

**Related Bills**
-The related bills should be listed as  H.R. 1234 not 116hr1234

**Recent Actions**
-Include any actions that happened for the bill within the last two weeks

**Prognosis** 
-Pull data from GovTrack

**Read Bill**
"Read Bill" button should be moved to the bottom of the overview section. When the user clicks on the "Read Bill" button, it should take them to a PDF of the full bill

**Comment by aih** [comment]
Closing as outdated. We can re-open with a more up-to-date requirement.
