### ISSUE TITLE
Understand the Context - Place tabs in correct order

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#103]
![image](https://user-images.githubusercontent.com/69854688/102914932-f8f6e500-444e-11eb-8de5-21d66e3b2569.png)

The tabs should be in the following order:
- Committee Documents
- CRS Reports
- CBO Scores
- Press Statements
- Statement Administration Policy
- Floor Proceedings

**Comment by nkinaba** [comment]
Duplicate issue ticket

https://github.com/aih/FlatGov/issues/63
