### ISSUE TITLE
Add "Currently in Congress" column  to the "Sponsors of Related Measures" section

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#108]
![image](https://user-images.githubusercontent.com/69854688/103020306-29558680-4516-11eb-9bf5-5f4e7ece8998.png)

The last column should show if the congressperson is in the current congress or not

**Comment by nkinaba** [comment]
As a user, I need the ability to see whether sponsors of related measures are still in congress or not.

**Comment by nkinaba** [comment]
<img width="1276" alt="Screen Shot 2020-12-28 at 11 27 21 AM" src="https://user-images.githubusercontent.com/69855502/103228816-a9f1f980-48ff-11eb-9c34-4c3a085e173b.png">

**Comment by aih** [comment]
Implemented in the top table. The Sponsors of Related measures section *only* shows current members
