### ISSUE TITLE
Search bar should have filter for Congress session (ex: 116th, 115th, 114th etc.)

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#111]
![image](https://user-images.githubusercontent.com/69854688/103022177-72f3a080-4519-11eb-9e8d-b657121ff61a.png)

Currently, the search bar on the demo presents itself without the filter. Please, use this image as a reference.

**Comment by nkinaba** [comment]
As a user I need the ability to filter my bill search by congress session first, then enter the bill number

**Comment by aih** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/217356/112403869-7a6b4700-8ccc-11eb-8cb3-84c8032682e3.png)
![image](https://user-images.githubusercontent.com/217356/112404082-e352bf00-8ccc-11eb-9391-cc857883b0e8.png)
