### ISSUE TITLE
Advanced Search should fit the size of the entire width of the search bar on the top

### ISSUE THREAD

**Issue by juancholarra** [aih/FlatGov#117]
<img width="643" alt="Screen Shot 2020-12-28 at 1 02 04 PM" src="https://user-images.githubusercontent.com/69854688/103234361-7f0ea200-490d-11eb-9270-c645cb554df4.png">

The advanced search part on the bottom of the search bar section should be the same width size as the sum of the entire width of the regular shown in the picture.

**Comment by nkinaba** [comment]
<img width="1190" alt="Screen Shot 2021-02-02 at 11 25 16 AM" src="https://user-images.githubusercontent.com/69855502/106629924-5485b980-6549-11eb-9f50-8e7ea3f11af8.png">
