### ISSUE TITLE
Fix routing for pdfs for SAPs

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#139]
The link from the bills page goes to `/bills/statements`:
![image](https://user-images.githubusercontent.com/217356/106212644-e2475a80-617f-11eb-9fab-4513cc27a99e.png)

But it should go to `/media/statements`:
![image](https://user-images.githubusercontent.com/217356/106212698-fdb26580-617f-11eb-9c16-34238a89bf1b.png)

**Comment by ayeshamk** [comment]
I checked the links. They are routing to the correct directory i.e. media/statements as you can see below. You may have old tables and data. Try deleting the old table, data and reloading data and tables.


![image](https://user-images.githubusercontent.com/13549492/106311833-c0a7ab00-6233-11eb-932f-98d808f2ca50.png)

**Comment by aih** [comment]
Thanks for checking. I'll need to rebuild my tables.
