### ISSUE TITLE
Change title of sponsor section from "Sponsor" to "Sponsors of Related Measures" 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#146]
<img width="1161" alt="Screen Shot 2021-02-04 at 12 51 13 PM" src="https://user-images.githubusercontent.com/69855502/106934066-ab28fa00-66e7-11eb-9cbc-7cf3b2f4a0d8.png">

<img width="1278" alt="Screen Shot 2021-02-04 at 12 56 42 PM" src="https://user-images.githubusercontent.com/69855502/106934697-6ea9ce00-66e8-11eb-8d75-c9366d90cd7e.png">

**Comment by aih** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/217356/112565570-8291b800-8d9a-11eb-9088-44c8f566a6e2.png)
