### ISSUE TITLE
UI Updates for Sponsors of Related Measures

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#147]
The UI for Sponsors of Related Measures 
1. Change the second tab from "This Congress" to "Current Congress"
2. Change the column order and add in columns to reflect the image below (Sponsors, Party, Date Sponsored, Committee(s), Position, Bill, Currently in Congress)

<img width="1263" alt="Screen Shot 2021-02-04 at 1 05 45 PM" src="https://user-images.githubusercontent.com/69855502/106935703-b2510780-66e9-11eb-9e9e-ee39ceca1dc4.png">

**Comment by aih** [comment]
From Josh:

>Committee membership data:

>Unclear if you need this. You won't fetch committee reports based on the committees a cosponsor sits on because you will do it by bill referral, and although you could prioritize/sort reports based on whether there are cosponsors on the committee, I don't anticipate that that would be a useful sort order.
>The committee membership data can be found in the >https://github.com/unitedstates/congress-legislators/ project. Right now there is some missing data because we're still close to the start of the Congress. committee-membership-current.{yaml,json} has current committee assignments and can be cross-walked with bioguide IDs. There is no historical committee assignments data (except in the git history).

**Comment by aih** [comment]
We have implemented most of these. The 'Currently in Congress' column is now a separate issue (#322). Closing.
