### ISSUE TITLE
UI Sprint 1 _ Overview Section 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#161]
**Current Display** 
<img width="560" alt="Screen Shot 2021-02-11 at 11 22 25 AM" src="https://user-images.githubusercontent.com/69855502/107665431-6bb85b80-6c5b-11eb-963e-1592545e3ef7.png">

**Wireframe**
<img width="609" alt="Screen Shot 2021-02-11 at 11 22 55 AM" src="https://user-images.githubusercontent.com/69855502/107665507-7e329500-6c5b-11eb-9382-8ebe9a9b8482.png">

1. The container title should be displayed as "Overview"

2. The categories in the Overview section should be listed in the following order: 

**-Bill Summary:**
**Leave section blank until information is scraped

**-Bill Stage:**

**-Related Bills:**
**The display of the bill number will be fixed at a later time from EX: 116hr736 to H.R. 736

**-Recent Actions (in focus):**

**-Prognosis:**

**-Read Bill:** 
The "Read Bill" button should be moved and centered at the bottom of the container as displayed in the second picture (above)

**Comment by ayeshamk** [comment]
done
