### ISSUE TITLE
UI Sprint 1 _ Bills Related to 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#164]
**Current Display**

<img width="1069" alt="Screen Shot 2021-02-11 at 1 07 40 PM" src="https://user-images.githubusercontent.com/69855502/107679072-1f284c80-6c6a-11eb-80b2-b35413ccd02b.png">

**Wireframe**

<img width="1245" alt="Screen Shot 2021-02-11 at 1 13 49 PM" src="https://user-images.githubusercontent.com/69855502/107679781-fd7b9500-6c6a-11eb-8ca1-201b0b0a417c.png">

1. Change to section heading from  "Analyze Related Bills" to "Bills Related to (insert bill number ex: Bills Related to H.R. 736)"

2. Change the column titles and order to: Bill Number, Lead Sponsor, Chamber, Status, Compare Bill
** Another column will be added to indicate the relationship of the bill

3. Include a dummy "Compare" button under the Compare Bill column

**Comment by ayeshamk** [comment]
done
