### ISSUE TITLE
UI Sprint 1 _ Sponsors Section Heading Change

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#165]
**Change the section heading from "Sponsors" to "Sponsors of Related Measures"**

**Current**

<img width="1092" alt="Screen Shot 2021-02-11 at 1 09 34 PM" src="https://user-images.githubusercontent.com/69855502/107679295-644c7e80-6c6a-11eb-89f7-afeca226a028.png">

**Wireframe**

<img width="1284" alt="Screen Shot 2021-02-11 at 1 21 59 PM" src="https://user-images.githubusercontent.com/69855502/107680649-20f30f80-6c6c-11eb-8e1e-a4a48d3cd02a.png">

**Comment by aih** [comment]
This has been implemented:
![image](https://user-images.githubusercontent.com/217356/112565257-fbdcdb00-8d99-11eb-9303-4cb2001cf573.png)
