### ISSUE TITLE
UI Sprint 1 _ Bill Page "Folder" Containers

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#166]
Touch up the containers to make them look as close to the design in the wireframes. Make the containers look more "realistic" i.e. folder like

<img width="1234" alt="Screen Shot 2021-02-11 at 1 27 04 PM" src="https://user-images.githubusercontent.com/69855502/107681264-d625c780-6c6c-11eb-9e71-1853632bd989.png">

**Comment by ayeshamk** [comment]
done
