### ISSUE TITLE
Re-style tabular table to match UX 

### ISSUE THREAD

**Issue by zomdar** [aih/FlatGov#18]
Currently the tabular implementation of the tables don't match the UX. We'll need to implement the current CSS in bootstrap tables to reskin the tabular tables.

Tabular: 
<img width="1084" alt="Screen Shot 2020-09-14 at 11 09 51 PM" src="https://user-images.githubusercontent.com/7513454/93160946-76d48300-f6df-11ea-8ca9-97254367277c.png">

Current bootstrap iteration (matching UX):
<img width="1089" alt="Screen Shot 2020-09-14 at 11 10 02 PM" src="https://user-images.githubusercontent.com/7513454/93160981-8bb11680-f6df-11ea-8f73-bf504886b687.png">

**Comment by aih** [comment]
Check with Charlotte re. the styling. We probably do want to update styling the table, but not necessarily to match the existing tables, which are static. For example, we will need to handle overflow text (e.g. in the 'Shared cosponsors') column.

Some of the styling in tabulator is functional: the vertical dividers are selectable/dragable. The rows in tabular are also styled to be selectable. While we have not implemented a select function for the rows, we may (e.g. selecting a row populates the Sponsors table, or opens that bill in a new browser tab).

Take a look at the themes provided for Tabulator, to see if we can re-use or extend one of these:
http://tabulator.info/docs/4.1/theme

**Comment by zomdar** [comment]
Oh neat, it already has a bootstrap theme that we can implement. In that case, lets just import the bootstrap theme for now and match the style. Once that's finished, ux can guide us on fleshing out features like row selection. 

I'll open up issues for the other static tables, which need to be hydrated with relevant data.

**Comment by aih** [comment]
Also adjust the tabulator settings to make it responsive. See http://tabulator.info/docs/4.1/layout

**Comment by aih** [comment]
The styling looks good. However, the sponsors table should be in the Sponsors section (not 'Understand the Context') and should use the data in the sponsors_table object in `master`:
```var sponsors_table = JSON.parse(`{{ bill.cosponsors_table|safe|escapejs }}`);```

![image](https://user-images.githubusercontent.com/217356/94632416-482ddf00-027f-11eb-9a63-dff9e5761a27.png)

**Comment by aih** [comment]
I tried to merge `master` into `home-page`, but it did not create the right merge. @zomdar Can you bring the styling into the current `master`?

**Comment by zomdar** [comment]
yea i think we can just merge `home-page` branch into master. The table styling should be copied over through this branch. The tabes in 'understand the context' was hard coded to test the tabular styling, i've removed it and put a todo to replace it with a hydrated table.

**Comment by aih** [comment]
Closed witht he merging of #33
