### ISSUE TITLE
Develop the Relevant Committee Documents section - Database, Back-end and UI development

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#180]
![image](https://user-images.githubusercontent.com/13549492/108083518-258b3f80-7041-11eb-95bf-421fd9a8e97b.png)

**Comment by ayeshamk** [comment]
Per Daniel: in addition to the above attributes, we also want to include "Report Number"

**Comment by aih** [comment]
This is working as of 1fda406269

![image](https://user-images.githubusercontent.com/217356/110539120-b2be3300-80d9-11eb-9053-ad6a599c939c.png)
