### ISSUE TITLE
Fix encoding for CRS report titles

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#188]
![image](https://user-images.githubusercontent.com/217356/108103431-c75d5d00-703e-11eb-9484-877d33bfdedf.png)

E.g. `Membersâ Representational Allowance: History and Usage`

**Comment by JoshData** [comment]
I couldn't quickly get the code to run, but I extracted the few lines that fetch the everycrsreport CSV file to see what's happening.

Replacing `r.text` with `r.content.decode("utf8")` on line 22 (`reader = csv.DictReader(r.text.splitlines())`) should fix it.

The MIME type set on the file in S3 is probably wrong or missing charset info.

**Comment by aih** [comment]
Fixed in #404 

This won't fix the data or display until/unless we reprocess the CRS data
