### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by zomdar** [aih/FlatGov#19]
This feature is to implement the home page based on the UX wireframe:
https://preview.uxpin.com/74759f3657712ac7dd6218004869a3c263dec460#/pages/132039538/simulate/no-panels?mode=i

- [x] Create Home page template
- [x] Configure header to route to home page
- [x] Create search bar
    - [x] Implement typeahead
    - [x] Implement search functionality to route users to /bills/{billNumber}
- [ ] Discuss "whats happening this week" feature with UX to create requirements

**Comment by aih** [comment]
Closing this issue, with the merging of #33 .
