### ISSUE TITLE
Committee report has wrong 'billnumber'

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#191]
Working on the `feature/committee-reports-cherrypick` branch.

The item in 'billnumber' in the CommiteeDocuments table is not really a billnumber, but a report name or report number. The field should be renamed. A consequence of this is that the wrong bill is being linked to the report. In the case below, for example, the report name is `H. Rep. 115-765`, but the bill it refers to is correctly identified in the `associated_legislation` field. Here, the report is shown under *bill* 115hr765, when it should not be there. It should instead be shown for bill `115hr6147`

![image](https://user-images.githubusercontent.com/217356/109201460-b7d4c700-7756-11eb-9b5a-b448e0aa98aa.png)

![image](https://user-images.githubusercontent.com/217356/109201718-02eeda00-7757-11eb-98ad-d42ad55dc28d.png)

**Comment by ayeshamk** [comment]
fixed in feature/UI_Enhancements_Ayesha branch

**Comment by aih** [comment]
@ayeshamk can you make this fix in the feature/committee-reports-cherrypick branch? If you have a plan to work with @leedavidr to merge the Committee documents to main, you can ignore this.

**Comment by aih** [comment]
This works in the scraper we've now merged to `main`.
![image](https://user-images.githubusercontent.com/217356/110538786-4a6f5180-80d9-11eb-8c19-bd5cb98aeb3e.png)

Closing.
