### ISSUE TITLE
Display committee documents on the bill corresponding to `associated_legislation`

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#192]
Working on the `feature/committee-reports-cherrypick` branch. Related to #191 

For example, this report should be associated with `115hr6147`, not bill `115-765`. To do this correctly, we need to store the Congress number as well. This can either be a new `congress` field, or add it to the `associated_legislation` field and normalize so that the field contents look like `115hr6147`, not `H.R. 6147`.

![image](https://user-images.githubusercontent.com/217356/109203402-f4a1bd80-7758-11eb-9195-38dc436e3243.png)

![image](https://user-images.githubusercontent.com/217356/109203638-40546700-7759-11eb-8927-8691ed9779e6.png)

**Comment by ayeshamk** [comment]
fixed in feature/UI_Enhancements_Ayesha branch

**Comment by aih** [comment]
@ayeshamk can you make this fix in the `feature/committee-reports-cherrypick` branch? If you have a plan to work with @leedavidr to merge the Committee documents to `main`, you can ignore this.

**Comment by aih** [comment]
This is working in `main`, with the latest scraper.
