### ISSUE TITLE
Scrape the current Biden Statements of administration policy

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#203]
Data is at this URL: https://www.whitehouse.gov/omb/statements-of-administration-policy/

**Comment by aih** [comment]
Use scrapy for this, and add the scraper to `scrapers` as a separate directory. Before starting, review the `statementAdminPolicy` directory. Update this to scrape current Whitehouse SAPs, or delete this directory and create a new one (also named clearly so we know it refers to Statements of Administration Policy). All scrapers and any data for this scraper should go inside its own directory (see #210).

**Comment by ayeshamk** [comment]
done
