### ISSUE TITLE
Daniel's Home Page Feedback

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#207]
(1) Header Content

- [x] (a) Rename "Bill Navigator to "Bill Map."

- [x] (b) Change description to "We put federal legislation in context by showing congressional actions, the history of legislation, and what might happen next"

- [ ] (c) Move this section lower.

(2) Search box

- [ ] (a) Break search box into two boxes. The largely one on the left is the open field. The small one on the right contains a drop down to choose the congress, with the default of current congress.

- [x] (b) In the search box, include the language "Search for bills and resolutions". After that, include examples of what that looks like, e.g. H.R. 1, H. Res 5"

- [ ] (c) Move this to the top

(3) Calendar

- [x] (a) The calendar does not appear to be showing this week's committee proceedings. (We may be be able to ride off GovTrack's work)

- [ ] (b) Add "year" after "week" and "month" for faster toggling. Year could also include the House & Senate floor calendar. (this would be a new feature, so we can exclude)

**Comment by aih** [comment]
>Move this section lower.

>Move this to the top

Not clear here, or in the original email what 'this' refers to (screenshot may not have come through)

The week is *currently* shown, but there may be inconsistencies in the Calendar API:

![image](https://user-images.githubusercontent.com/217356/116267694-8023d480-a731-11eb-8a2e-126a52348ac9.png)

Closing this issue in favor of future review and feedback.

**Comment by DanielSchuman** [comment]
The "move this lower" referring to aligning the search boxes so they were
on the same vertical plan. They had previously been misaligned. Thanks!
