### ISSUE TITLE
Remove "Read Bill:" from Overview section

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#215]
Remove **"Read Bill:"** just display the read bill button

<img width="521" alt="Screen Shot 2021-03-12 at 10 39 16 AM" src="https://user-images.githubusercontent.com/69855502/110962799-5e0bf980-831f-11eb-8870-e246000fd570.png">

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/112369657-acaf8100-8c99-11eb-963a-ce8e486acbb3.png)
