### ISSUE TITLE
Have the "View full list of sponsors" button scroll down the page to "Sponsors of Related Measure" 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#216]
As a user I need the ability to click on the "View full list of sponsors" and have the page scroll down to the "Sponsors of Related Measures" section 

<img width="530" alt="Screen Shot 2021-03-12 at 10 43 50 AM" src="https://user-images.githubusercontent.com/69855502/110967258-2eabbb80-8324-11eb-8368-07960ea9e3f6.png">

**Scroll to this section on the bill page**

<img width="1510" alt="Screen Shot 2021-03-12 at 10 44 02 AM" src="https://user-images.githubusercontent.com/69855502/110964930-b93eeb80-8321-11eb-91ba-e1cf61d94600.png">

**Comment by aih** [comment]
Working.
