### ISSUE TITLE
Add tabs to the "Bills Related to _________" section

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#217]
**Add "Current Congress" and "All Congresses" tabs to the "Bills Related to____" section as seen in the wireframe** 

**Current View**

<img width="994" alt="Screen Shot 2021-03-12 at 11 16 28 AM" src="https://user-images.githubusercontent.com/69855502/110967493-6c104900-8324-11eb-9eab-21d2bce9bcbc.png">

**Wireframe**

<img width="932" alt="Screen Shot 2021-03-12 at 2 12 43 PM" src="https://user-images.githubusercontent.com/69855502/110987494-2613af00-833d-11eb-8eaf-7c37c61f7b94.png">

**Comment by aih** [comment]
I believe this is a duplicate of #84. @nkinaba, @smplater can you review old issues and consolidate?

**Comment by aih** [comment]
Working
