### ISSUE TITLE
Change the title on homepage to "Bill Map" and add description 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#219]
On the homepage change "Bill Navigator" to "Bill Map" and add the following for the description  

"We put federal legislation in context by showing congressional actions, the history of legislation, and what might happen next"

<img width="1866" alt="Screen Shot 2021-03-12 at 11 58 19 AM" src="https://user-images.githubusercontent.com/69855502/110972694-45551100-832a-11eb-9dc8-1ab7534f8c6c.png">

**Comment by aih** [comment]
Implemented in #246
