### ISSUE TITLE
Change the display formatting of the bills to "H.R. XXX"

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#221]
Change the display formatting of the bills as seen in the wireframe  

**EX: H.R. Bill# (Congress session)  -->  H.R. 736 (116)** 

**Bill type abbreviations** 
House Bill: H.R.
House Joint Resolution: H.J.Res.
House Concurrent Resolution: H.Con.Res.
House Resolution: H.Res.
Senate Bill: S.
Senate Joint Resolution: S.J.Res.
Senate Concurrent Resolution: S.Con.Res.
Senate Resolution: S.Res.

**Current View**

<img width="542" alt="Screen Shot 2021-03-12 at 12 36 41 PM" src="https://user-images.githubusercontent.com/69855502/110977446-2ce7f500-8330-11eb-8e52-da6be0b71e7d.png">

**Wireframe**

<img width="589" alt="Screen Shot 2021-03-16 at 3 06 31 PM" src="https://user-images.githubusercontent.com/69855502/111365737-3b544a80-8669-11eb-83f3-4330d11af78c.png">

**Comment by DanielSchuman** [comment]
Just a note:

We should make sure we use the right prefix.

Here is how Congress.gov does it -- showing the acceptable ways that one
can search for different kinds of legislation:
https://www.congress.gov/help/search-tools-overview#toggler-search-by-number

The top one they list is the official way to display.

We want for:
House Bill: H.R.
House Joint Resolution: H.J.Res.
House Concurrent Resolution: H.Con.Res.
House Resolution: H.Res.
Senate Bill: S.
Senate Joint Resolution: S.J.Res.
Senate Concurrent Resolution: S.Con.Res.
Senate Resolution: S.Res.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/111855772-b7f25d80-88e3-11eb-8968-3ba518fb9956.png)
![image](https://user-images.githubusercontent.com/217356/111855777-c04a9880-88e3-11eb-9441-fc75b1b702ce.png)
![image](https://user-images.githubusercontent.com/217356/111855789-d35d6880-88e3-11eb-9cea-fda5df73e5f9.png)
