### ISSUE TITLE
When the user is on a bill page, the Bill tab in the nav should be highlighted

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#245]
The Home tab is currently highlighted when the user is on a bill page. 
![Image+2021-03-23+at+9 30 25+AM](https://user-images.githubusercontent.com/60105995/112154202-6a634280-8bba-11eb-8a66-1f3e3bde623b.png)

**Comment by aih** [comment]
The `Home` and `Bills` highlighting works
![image](https://user-images.githubusercontent.com/217356/117079334-6580cb00-acf0-11eb-9b7e-5556327a1898.png)

But not on an individual page:
![image](https://user-images.githubusercontent.com/217356/117079394-8517f380-acf0-11eb-8086-75f8518c434e.png)

**Comment by aih** [comment]
Working now in c5ef073:
![image](https://user-images.githubusercontent.com/217356/117080253-500ca080-acf2-11eb-9412-51161fdd9d37.png)
