### ISSUE TITLE
Upon first opening the 'All Congresses' tab of Related Bills, the headings are compressed

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#247]
![image](https://user-images.githubusercontent.com/217356/112174652-d0000080-8bb3-11eb-8273-4f25743d6b21.png)

**Comment by weinicookpad** [comment]
I pulled the code from main branch and run it on my local.
![image](https://user-images.githubusercontent.com/72507809/112316937-86640280-8ce6-11eb-990e-1f019ae078dd.png)
It works well on my side.

**Comment by aih** [comment]
This may have been a caching issue. Closing.
