### ISSUE TITLE
Show 'No data available' if and only if there's no data

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#250]
Currently, the 'No Data available' message:
1. Always appears in the Committee Documents tab, even if there is data
![image](https://user-images.githubusercontent.com/217356/112366715-60af0d00-8c96-11eb-9679-fc2247e02d4f.png)

2. When there is no data, the table headings show anyway
![image](https://user-images.githubusercontent.com/217356/112366758-6c023880-8c96-11eb-8ad0-4e33374f755e.png)

We want:
1. Do not show the message if there is data in the table
2. Do not show the table headings if there is no data

**Comment by ayeshamk** [comment]
done
