### ISSUE TITLE
Separate out the search bars

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#253]
This is related to the search from the Home page. @nkinaba, @smplater what does this issue refer to? Can you provide more details of what the desired behavior is?

**Comment by smplater** [comment]
See #111 for more details

**Comment by aih** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/217356/112403869-7a6b4700-8ccc-11eb-8cb3-84c8032682e3.png)
![image](https://user-images.githubusercontent.com/217356/112404082-e352bf00-8ccc-11eb-9391-cc857883b0e8.png)
