### ISSUE TITLE
Provide consistent bill number display, e.g. H. R. 1500 (116)

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#254]
This is implemented with the `billnumber_display` filter in `flatgov/bills/templatetags/bill_filters.py`. 

Now also added to the 'Similar Sections' tab

Before
![image](https://user-images.githubusercontent.com/217356/112374828-cd7ad500-8c9f-11eb-8d2a-0b381daa4246.png)

After
![image](https://user-images.githubusercontent.com/217356/112375384-7d504280-8ca0-11eb-9cc0-4558b992e2b5.png)

**Comment by aih** [comment]
@smplater , @nkinaba Can you check whether there are any other places this is missing?

**Comment by nkinaba** [comment]
<img width="1048" alt="Screen Shot 2021-03-25 at 10 23 59 AM" src="https://user-images.githubusercontent.com/69855502/112489135-8a2e6e00-8d54-11eb-9f74-e154c7397409.png">

**Comment by aih** [comment]
This one has been updated: ![image](https://user-images.githubusercontent.com/217356/112563104-f382a100-8d95-11eb-8fb5-cc4d764c43ff.png)

**Comment by aih** [comment]
I'm closing this now. We can re-open another issue if other examples of inconsistent display are found.
