### ISSUE TITLE
Monthly View on Calendar should start on Monday

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#257]
The current display for Monthly View on the Calendar starts on Sunday and the holiday events are off by one day. 

Current Display:
![Image+2021-03-24+at+4 30 43+PM](https://user-images.githubusercontent.com/60105995/112379339-6c162e80-8cbe-11eb-97ee-bd6509d442c2.png)

**Comment by aih** [comment]
This is either fixed, or it is a function of the date/time on the server. This may also affect the display of calendar events on Sunday, which are meant for Monday.

This image was taken at 5:25pm PST / 8:25pm EST:

![image](https://user-images.githubusercontent.com/217356/117085138-d4b0ec00-acfd-11eb-9b38-0efa8afdb55f.png)

**Comment by leedavidr** [comment]
This was just a setting on the full calendar JS
"firstDay"

https://github.com/aih/FlatGov/commit/786224cc901660bb844f5f38bdbc1538461831b2#diff-20f30d77eb90d9aec7b07fda58c1ab9b0788584368670e128bc5d40a82ed34db

It should impact all views I think
We can close if we don't see this issue anymore

**Comment by leedavidr** [comment]
I'll close actually, we can re open if this is still visible somewhere!
