### ISSUE TITLE
Add Committee and Party information to Sponsors

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#259]
This is a question of priority: associating sponsors with party and committee may be time consuming and duplicates work already done on govtrack. If/when this repo is integrated with govtrack, we can just re-use the cosponsor data there.

**Comment by aih** [comment]
Assigning to @DanielSchuman, @smplater an @nkinaba   to discuss priority-setting

**Comment by smplater** [comment]
As discussed on March 30th, @DanielSchuman set this item as a priority for that week. 

Scraper and file to populate the cosponsor information:
https://github.com/unitedstates/congress-legislators/ 

The hierarchy of cosponsors will be discussed at a later time
Change text “View full list of sponsors” button → Text will be provided once established

**Comment by aih** [comment]
The remaining work for this issue is in #305
