### ISSUE TITLE
Why is Celery task called from View?

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#260]
In the views.py, there is the following code. I've commented out two lines that appear to trigger a scraping task. Is there a reason that is there?

```Python
class BillListView(TemplateView):
    template_name = 'bills/list.html'

    def get_context_data(self, **kwargs):
        #from uscongress.tasks import bill_similarity_task
        #bill_similarity_task(26)
        context = super().get_context_data(**kwargs)
        return context
```

**Comment by kapphire** [comment]
We need to remove those 2 lines.
I debugged the celery tasks by adding those 2 lines on my side.

**Comment by aih** [comment]
Great. It's already commented out.
