### ISSUE TITLE
The congress filter should be on the same line as the search bar and include arrow

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#270]
1. The filter for congress needs to be on the same line as the search bar as seen in the second image (wireframe)
2. The filter should include an arrow (circled in the wireframe image) that lets users know they have the option to filter their search by congress
3. 117th should be the default for the filter

**Current View**
<img width="1272" alt="Screen Shot 2021-03-31 at 2 17 19 PM" src="https://user-images.githubusercontent.com/69855502/113191660-d0d80880-922b-11eb-8e4b-e06e6d3fda1b.png">

**Wireframe**
<img width="1303" alt="Screen Shot 2021-03-31 at 2 22 38 PM" src="https://user-images.githubusercontent.com/69855502/113193122-9e2f0f80-922d-11eb-9d03-77f441f8af1c.png">

**Comment by aih** [comment]
Implemented and deployed:
![image](https://user-images.githubusercontent.com/217356/113747676-7cfe7100-96bc-11eb-9723-cbaad5e46c35.png)
