### ISSUE TITLE
Search bar input format

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#271]
1. Remove spaces and periods for the search bar to allow the user to enter different formats to get the same search results

Ex: 
**Current function** - Results only appear when the user inputs the bill type and number without spaces **hr1234, sres1500, s1200**

The search bar should include the following input formats and still populate results **hr 1234, sres 1500,  s 1200 or h.r. 1234, s.res. 1500, s. 1200**

**Comment by aih** [comment]
Now consistently formatted:
![image](https://user-images.githubusercontent.com/217356/113462602-8941b000-93d6-11eb-95f8-9d18f168d799.png)

Closing
