### ISSUE TITLE
Put examples of search formats below the search bar & changes to reflect wireframe

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#272]
1. Input search formats below the search bar as seen in the wireframe 
2. Change grey text inside the search bar to “Search for Legislation”
3. Remove prompt “Search for Legislation, Committee Materials, Congressional Record, or Members of Congress with basic or advanced search settings.”
4. Include "th" for the congress filter for all sessions  EX: 117th, 116th

Wireframe
<img width="1257" alt="Screen Shot 2021-04-06 at 3 25 16 PM" src="https://user-images.githubusercontent.com/69855502/113786802-e2c41a80-9707-11eb-88fe-b7b9a7f1c27a.png">

**Comment by aih** [comment]
What is the exact text that should go in the search bar? Currently, typing H.R. 200 or hr200 or 200 will pull up results, as will HJRES1500 , HjRes, H.J.RES1500 and more.

**Comment by aih** [comment]
The search is case insensitive, removes spaces and supports search with and without periods.

So the example text could be:
`Examples: s5, hr5, hres5, hjres5, hconres5, sjres5, sconres5, sres5`

The stages are:
`'S.', 'H.R.', 'H.Res.', 'H.J.Res.', 'H.Con.Res.', 'S.J.Res.', 'S.Con.Res.', 'S.Res.'`

**Comment by aih** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/217356/114240196-0079c580-993c-11eb-8988-26b9ec7fae41.png)

**Comment by smplater** [comment]
The examples of the Bills that can be searched should be below the search bar not in the search bar, as the wireframe shows below. "Search for Legislation" should be the text in the search bar.
<img width="1257" alt="113786802-e2c41a80-9707-11eb-88fe-b7b9a7f1c27a" src="https://user-images.githubusercontent.com/60105995/114432419-acb2ea80-9b8e-11eb-9845-dff3b2223bc0.png">

**Comment by aih** [comment]
@ayeshamk see the mock-up above. The 'Search for legislation' text will be in italics, as `@placeholder` text.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/117079127-0753e800-acf0-11eb-986b-7e2c1ffd6871.png)
Implemented in PR #341
