### ISSUE TITLE
Read Bill button 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#274]
The "Read Bill" button in the overview section should link to the full report on GovTrack

**Comment by aih** [comment]
Working:
![image](https://user-images.githubusercontent.com/217356/113747528-52141d00-96bc-11eb-9554-c538d88e8db7.png)
![image](https://user-images.githubusercontent.com/217356/113747552-5a6c5800-96bc-11eb-986c-ec1e455d73a5.png)
