### ISSUE TITLE
Press Statements 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#275]
- [ ] 1. Remove Chamber Column and put Sen. or Rep. before the issuer name
- [x] 2. Date should be in this format "Month XX, XXXX" 
- [x] 3. Remove Bill Column

**Comment by aih** [comment]
Note: the formatting can/should be done a standard date filter or with filters in the bills/templatetags directory

**Comment by ayeshamk** [comment]
Removed the bill column. Per Daniel, the rest of the changes are not a priority right now.

**Comment by aih** [comment]
Added date formatting with a Vue + momentjs filter
