### ISSUE TITLE
Press Statements: Change architecture and show results instantly using direct API calls

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#280]
Fetching and loading data to DB caused few seconds of delay. Changed the code architecture accordingly and used AJAX request instead. This made the results appear instantly.

**Comment by aih** [comment]
Implemente, merged to `main` and deployed::
![image](https://user-images.githubusercontent.com/217356/113455357-3f010480-93bf-11eb-8650-2c61a8df0858.png)
