### ISSUE TITLE
Related Bills in Overview section - include only related bills from the current congress and change display

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#290]
1. Limit related bills in Overview section to related bills in the current congress only 

2. Include the short title (if available) or title up to x amount of characters in a hover over 

<img width="603" alt="Screen Shot 2021-04-06 at 6 57 26 PM" src="https://user-images.githubusercontent.com/69855502/113787966-00927f00-970a-11eb-8767-8d7141905cd6.png">

**Comment by aih** [comment]
@ayeshamk, note that in the latest `main`, I have updated the display to include the ordinal (117_th_), by updating the billnumber display filter.

I've also added a new route, e.g. `/home/bill-titles/117` (serving the class BillListTitleAPIView(View) in `home/views.py`) that gives a dictionary of billnumber: short title, if that is helpful in creating the `title` attribute for the related bill list. You may also get the short title from the related bills themselves, as we do in the table:

![image](https://user-images.githubusercontent.com/217356/113908217-2449d980-978b-11eb-8019-b3d797ac5106.png)

**Comment by aih** [comment]
Implemented
