### ISSUE TITLE
Readme Changes

### ISSUE THREAD

**Issue by adamwjo** [aih/FlatGov#3]
#2 

Did you still want to include the info on the scraper? Or perhaps a caveat about it actually taking a long time to run?

Also noting the `$ python3 <filename>` command with macs. Python novice here, so wasn't immediately apparent the difference between the commands "python" and "python3". 

I think some language describing in better detail where the congress data should exist in the repo before you run the scripts would be nice. Also, some documentation on expected output when scripts are run successfully and unsuccessfully.

**Comment by aih** [comment]
The initial changes have been added. Closing.
