### ISSUE TITLE
Propagate Cosponsor table to the `cosponsor_dict` in the detail.html view

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#305]
There are now Cosponsor and Committee tables in the bills model, and a scraper in common.cosponsor.py that downloads, processes and loads those tables.

Meanwhile, the list of cosponsors of a bill is stored in a list within the bill table, `cosponsors_dict`.  For this issue, we:

1. Look up each item in the `cosponsors_dict`, 
2. Get the `committees` field for each cosponsor (the cosponsor's `bioguide_id` is unique). The committees field looks like: `[{"name": "Raphael G. Warnock", "rank": 7, "party": "majority", "bioguide": "W000790", "committee": "SPAG"}...]`
3. Filter this list by the `committees_dict` list associated with the bill (e.g. `[{"activity": ["referral"], "committee": "Senate Judiciary", "committee_id": "SSJU", "subcommittee": "", "subcomittee_id": ""}]`)
![image](https://user-images.githubusercontent.com/217356/114827958-2a891880-9d7e-11eb-96ab-6577b56939be.png)

4. For each committee that the cosponsor is on that is in the bill's `committees_dict`, add it to a `committees` field for that user in the `cosponsor_dict`. That is the information that goes into the 'On Assigned Committee(s)' column of the `Committees and Cosponsors` box in the top right, and the `Committees` column of the `Sponsors of Related Measures` section.

The Cosponsor model looks like:
![image](https://user-images.githubusercontent.com/217356/114827197-3b855a00-9d7d-11eb-9b6a-c72524a36346.png)

**Comment by aih** [comment]
I will create a dump of the database (about 2Gb) to make the Committee, Cosponsor and other data available, but the info above should be enough to get started on a branch for this issue.

**Comment by ayeshamk** [comment]
> There are now Cosponsor and Committee tables in the bills model, and a scraper in common.cosponsor.py that downloads, processes and loads those tables.

Is there a readme file with instructions on how to populate Cosponsor and Committee tables?

**Comment by aih** [comment]
There is a note on Cosponsors in https://www.github.com/aih/FlatGov/tree/main/DATA_BACKGROUND.adoc

It doesn't provide details. The cosponsors.py has an updateCosponsorsAndCommittees (check the spelling) function at the bottom. Running that will download the yaml files, process them and update the db tables.

**Comment by ayeshamk** [comment]
Implemented. Propagated data in both the top-right and the lower table.

![image](https://user-images.githubusercontent.com/13549492/115452357-52e49d00-a1ec-11eb-9333-070032c3b59c.png)
![image](https://user-images.githubusercontent.com/13549492/115452436-6bed4e00-a1ec-11eb-82df-615e70093d19.png)
