### ISSUE TITLE
Add column to indicate whether a cosponsor is no longer in Congress

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#322]
Related to #318

From discussion today: We will consider adding a column showing whether a cosponsor is a current member of Congress; the Cosponsors db table contains only current members, so if the bioguide id of the cosponsor is not in the Cosponsors table, the cosponsor is not currently in Congress.

Assigning @nkinaba and @smplater to add any prior mock-up we may have had for this feature and @DanielSchuman to suggest what the column should show (e.g. Yes/No for current membership, or only a No for people who are not currently members?)

**Comment by nkinaba** [comment]
<img width="1333" alt="Screen Shot 2021-04-21 at 1 02 46 PM" src="https://user-images.githubusercontent.com/69855502/115593005-f5ab2300-a2a1-11eb-8375-661ea7f24e7a.png">

**Comment by aih** [comment]
We do not show cosponsors who are not in currently in Congress in the 'Sponsors of Related Measures' table; we get that data from the Bill-Cosponsors table, which only has current members.

So we can add the 'Currently in Congress' column to the Committees and Sponsors table in the top right.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/119079370-d4c31400-b9ac-11eb-9ee3-1e6c3d35a5a3.png)
