### ISSUE TITLE
Issue with the logic of "Sponsors of Related Measures" 

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#326]
"Sponsors of Related Measures" should have more records than the "Committee & Co-sponsors" Table. The top-right table is expected to show a subset of the lower table list. When the users click on "View Full List", they should see the full list.

However, I noticed for many bills, "Sponsors of Related Measures" has fewer records than "Committee & Co-sponsors". 

Attached one example below:

![image](https://user-images.githubusercontent.com/13549492/115914637-35a80c80-a440-11eb-9d21-0903be0fd32b.png)

When we click on "View Full List" we see a smaller list

![image](https://user-images.githubusercontent.com/13549492/115914668-3e98de00-a440-11eb-8c9e-8711c2ae32cf.png)

**Comment by aih** [comment]
The bottom table should be a super-set of the top table, but they're calculated differently. Per discussion with Daniel (see  #319) the bottom table will have not only the sponsors for the current bill (which the top table is drawn from), but also cosponsors of 'identical' bills from this and previous congresses.

**Comment by aih** [comment]
This issue no longer applies to the current Cosponsors table logic.

**Comment by aih** [comment]
This  appears to still be an issue in some bills:
![image](https://user-images.githubusercontent.com/217356/119076588-ad1d7d00-b9a7-11eb-87d8-6bebe5de58cb.png)
![image](https://user-images.githubusercontent.com/217356/119076613-b60e4e80-b9a7-11eb-9a54-b0ed5fbed57c.png)

**Comment by aih** [comment]
Collin C. Peterson is missing here because he is no longer a Member:
![image](https://user-images.githubusercontent.com/217356/119076723-eeae2800-b9a7-11eb-80ba-bd5a45490be6.png)

![image](https://user-images.githubusercontent.com/217356/119076775-04235200-b9a8-11eb-9d95-332ea5ea08c3.png)

**Comment by aih** [comment]
Fix in 6079d3afa to add lone sponsors to the Bill-Cosponsor Join table

**Comment by aih** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/217356/119090305-51abb900-b9c0-11eb-9ca7-2f4b451d13cc.png)
