### ISSUE TITLE
Search using just the bill number will populate results but the links route the user to a "page not found" page

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#327]
When the user enters just the number without the bill type (hr, s, hjres, etc.) the search will populate results but the links to those results routes the user to a "page not found" page. 

Example:

<img width="1164" alt="Screen Shot 2021-04-23 at 12 49 47 PM" src="https://user-images.githubusercontent.com/69855502/115923793-c4bb2180-a44c-11eb-9420-612f411b0df8.png">

<img width="1202" alt="Screen Shot 2021-04-23 at 12 50 16 PM" src="https://user-images.githubusercontent.com/69855502/115923802-cbe22f80-a44c-11eb-90b1-393af9d92ee5.png">

<img width="1159" alt="Screen Shot 2021-04-23 at 12 49 57 PM" src="https://user-images.githubusercontent.com/69855502/115923810-ce448980-a44c-11eb-95f5-fd1e65538f3f.png">

**Comment by aih** [comment]
This was due to the `hamdt` bills. We didn't include the acronym for them  in the list (`hamdt`). I've removed them from search, since we also don't have data for these bills.

**Comment by aih** [comment]
Getting the fix requires refreshing browser cache.
