### ISSUE TITLE
Review main and ensure enhancements have been added

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#344]
I've cherry-picked updates for the About page and calendar enhancements; the PR was merging with conflicts, since there were previous commits that were part of the branch.

Please review the current `main` (deployed to billmap.govtrack.us) to check for differences. Where there are differences, please create a new branch from `main` to implement the change (one small change at a time, for ease of re-merging).

One item I noticed is that the calendar key was lost in one of the updates, and I tried to restore it:

![image](https://user-images.githubusercontent.com/217356/117085951-12af0f80-ad00-11eb-996c-56bc9eb8f6cc.png)

We can discuss when you have time.

**Comment by ayeshamk** [comment]
I developed the calendar levels differently. They should be smaller and side-by-side.

**Comment by aih** [comment]
Can you point me to the code or commit?

**Comment by aih** [comment]
Got it. I added back in the parent div:
![image](https://user-images.githubusercontent.com/217356/117204910-c7e7d300-ada5-11eb-8dac-90138b4e21cf.png)

**Comment by aih** [comment]
Closing.
