### ISSUE TITLE
Develop API calls for Press statements

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#35]
Derek Willis may be able to point to the sources

**Comment by aih** [comment]
For current scraper:
https://www.whitehouse.gov/briefing-room/press-briefings/


If there is no more central location, we can scrape the earlier statements here:
https://trumpwhitehouse.archives.gov/briefings-statements/
https://obamawhitehouse.archives.gov/briefing-room/statements-and-releases
https://georgewbush-whitehouse.archives.gov/news/releases/2006/11 (organized by month and year)
https://clintonwhitehouse5.archives.gov/library/hot_releases/index.html


Example of a statement that mentions bills by number:
https://trumpwhitehouse.archives.gov/briefings-statements/h-r-3354-make-america-secure-prosperous-appropriations-act-2018/

https://georgewbush-whitehouse.archives.gov/news/releases/2006/11/20061117-14.html

**Comment by aih** [comment]
Bill number regex:

I realized I have a slightly different use case so I had to adapt the regex I use for what you would use with e.g. searching a CRS report's text. Hopefully I did it right:
bill_number_re = re.compile(r"(?P<type>h\.? ?r\.? ?|s\.? ?|h\.? ?con\.? ?res\.? ?|s\.? ?con\.? ?res\.? ?|h\.? ?j\.? ?res\.? ?|s\.? ?j\.? ?res\.? ?|h\.? ?res\.? ?|s\.? ?res\.? ?)(?P<number>\d+)", re.I)

def parse_bill_number(text):
    m = bill_number_re.match(text)
    if not m: return None
    return {
        "type": m.group("type").lower().replace(".", "").replace(" ", ""),
        "number": int(m.group("number"))
    }
Press statements for a bill:

Example function to call the propublica API plus some custom logic that tries to pick out a few key press statements:
https://github.com/govtrack/govtrack.us-web/blob/master/bill/views.py#L138

**Comment by JoshData** [comment]
This is what Daniel meant: https://projects.propublica.org/api-docs/congress-api/statements/

**Comment by aih** [comment]
This is working now, with AJAX calls from the UI.
