### ISSUE TITLE
Overview section and Committees and Sponsors section buttons should be positioned at the bottom of the sections

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#393]

**Comment by ayeshamk** [comment]
Currently, the buttons for the 2 sections are aligned as follows:
![image](https://user-images.githubusercontent.com/13549492/119393712-4cd85500-bc9f-11eb-9450-c13586e40113.png)

![image](https://user-images.githubusercontent.com/13549492/119393834-77c2a900-bc9f-11eb-821d-56cdc6fb957a.png)


**We'd like to achieve this:**

![image](https://user-images.githubusercontent.com/13549492/119393763-5eb9f800-bc9f-11eb-9428-e4d3414513f2.png)

**Comment by aih** [comment]
Working as specified (116hr1):
![image](https://user-images.githubusercontent.com/217356/119415325-3aade500-bca6-11eb-9c96-adb96cf07d88.png)
