### ISSUE TITLE
Home and Bill Page - Change background color

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#394]
Change background color to match the wireframe

**Comment by ayeshamk** [comment]
Change the background color of the pages from white to beige.

**Comment by aih** [comment]
Merged and deployed `feature/394-background`

**Comment by aih** [comment]
(Requires resetting browser cache to pick up the change.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/119400175-a2f0cc80-bc8e-11eb-8fe5-4e07f3fb7716.png)
