### ISSUE TITLE
Relevant Committee Documents: Get relevant committee documents for "identical" bills

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#398]
Relevant Committee Documents: Get relevant committee documents for "identical" bills as shown in the "Bills Related to" section.

![image](https://user-images.githubusercontent.com/13549492/119554474-b1acb180-bd6a-11eb-9b5a-70e7f1a2fff8.png)

Identical bills are shown here and there is a function that returns list of identical bills. @aih could you link the function here?

![image](https://user-images.githubusercontent.com/13549492/119554669-f33d5c80-bd6a-11eb-96c4-9df159f008b9.png)

**Comment by ayeshamk** [comment]
here is the function that returns identical bills: https://github.com/aih/FlatGov/blob/main/server_py/flatgov/bills/views.py#L310

**Comment by aih** [comment]
For cosponsors, I use a SQL query to get cosponsors for all of the identical bills. This can be done for committee documents, or repeat what we do for committee documents but loop over all of the identical bills. The table display may be messy and challenging to get right.
https://github.com/aih/FlatGov/blob/main/server_py/flatgov/bills/views.py#L321

**Comment by ayeshamk** [comment]
@DanielSchuman @aih For most bills, it appears that the identical bill is the bill itself. Do we want to include "nearly identical" bills' relevant committee documents too?

**Comment by aih** [comment]
Hi @ayeshamk, we are still working on a definition of 'identical' for this purpose.

If you support the list that is generated by the `get_identical_bills` function, we can update that function in the future (e.g. by including 'nearly identical' bills) to match users' expectations.

**Comment by aih** [comment]
The 'get_identical_bills' function already includes any bill in the list of IDENTICAL_REASONS. So, for example, 117hr200 is matched with bills from a number of different Congresses:

https://billmap.govtrack.us/bills/117hr200
![image](https://user-images.githubusercontent.com/217356/119715006-605afb80-be18-11eb-9bca-9e413a9d69ba.png)

**Comment by aih** [comment]
Working:
![image](https://user-images.githubusercontent.com/217356/119897640-90c49780-bef5-11eb-9003-d2f2d265ae41.png)
