### ISSUE TITLE
Fix styling for calendar dropdowns

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#411]
I've merged and deployed the `calendar4` branch updates. Tested on a laptop on Chrome.

There are a couple of possible problems with the styling of the dropdowns above the calendar:
1. The dropdowns take too much horizontal space (in my opinion). They go all the way across the calendar.
2. They also stack up on top of each other in a way that makes it hard to distinguish the Header (e.g. Committee) from the current selection (e.g. All)
3. There is very low contrast (at least for my colorblind eyes) between the black of the dropdown items and the calendar background.

![image](https://user-images.githubusercontent.com/217356/119751044-4e487f80-be4f-11eb-9121-dbcdf82af5ba.png)

**Comment by aih** [comment]
Assigning @leedavidr, but @smplater, @nkinaba or anyone else can chime in on design.

**Comment by leedavidr** [comment]
Oh yea sorry I just wanted to get everything hooked up asap before styling.
I think I’m going to be a bit busy in June

Main calendar functionality should be all in now

**Comment by aih** [comment]
This is the styling mockup from another issue:
![Image 2020-12-15 at 11 24 00 AM](https://user-images.githubusercontent.com/60105995/102242450-11ec1d00-3ec8-11eb-8fba-a1099b167e95.png)

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/120058619-08331d80-c001-11eb-8550-99dbc7af958d.png)
