### ISSUE TITLE
Sponsors of Related Measures: Link the bills to associated bills

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#414]
![image](https://user-images.githubusercontent.com/13549492/119883193-41826500-befd-11eb-8ceb-b0b9853e7ab6.png)

**Comment by ayeshamk** [comment]
@aih Hi Ari, I finished coding this issue on branch https://github.com/aih/FlatGov/tree/feature/related-measures-414. However, there is no data locally for me to test it under the sponsors of related measures section. If you have data, you might have to test it first locally before we deploy.

**Comment by aih** [comment]
Unfortunately, this solution removes the secondary bills:
![image](https://user-images.githubusercontent.com/217356/120012325-34fd1b80-bf94-11eb-83fc-d83184c32e1f.png)


I had done the same for 'All Congresses'. I will revert both PRs

**Comment by aih** [comment]
Some bills are not showing the same data as before, because we were calculating the bill sponsors incorrectly earlier.


It's working now to link the bills, though:
![image](https://user-images.githubusercontent.com/217356/120015595-59f38d80-bf98-11eb-935e-b2cb1b6c7a55.png)
