### ISSUE TITLE
Propagate 'identical' bills to context tabs: CRS

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#426]

**Comment by ayeshamk** [comment]
![image](https://user-images.githubusercontent.com/13549492/121728608-8391d600-cabb-11eb-9c60-a2f52c0b78c0.png)

**Comment by aih** [comment]
The CRS_Bills join table has these ids:
![image](https://user-images.githubusercontent.com/217356/121783228-42a0cc80-cb62-11eb-81ae-cc42dcace4f0.png)

**Comment by aih** [comment]
This query will get a list of CRS report ids, associated with a list of bill numbers:

```sql
SELECT id, bill_congress_type_number, crsAgg.crsids
FROM bills_bill 
LEFT JOIN 
(SELECT bill_id AS billid, STRING_AGG(crsreport_id::CHARACTER varying, ', ') AS crsids FROM crs_report_bills GROUP BY billid) crsAgg
ON bills_bill.id=crsAgg.billid
WHERE crsAgg.crsids IS NOT NULL
AND bill_congress_type_number IN ('117s917', '116hr1500')
GROUP BY bills_bill.id, crsAgg.crsids, crsAgg.billid;
```

**Comment by aih** [comment]
And this will aggregate the bill numbers. There may be a simpler way, but this works:

```sql
SELECT bctnAgg.crsid, bctnAgg.crsfile, bctnAgg.crstitle, bctnAgg.crsmetaurl, STRING_AGG(bctnAgg.bctn, ', ') AS bctns
FROM
(SELECT bctn, crs_report.id AS crsid, crs_report.file AS crsfile, crs_report.title AS crstitle, crs_report.meta_url AS crsmetaurl
FROM crs_report
LEFT JOIN
(SELECT bill_congress_type_number AS bctn, crsreport_id
FROM bills_bill
LEFT JOIN crs_report_bills ON bills_bill.id=crs_report_bills.bill_id
WHERE crs_report_bills.crsreport_id IS NOT NULL
AND bill_congress_type_number IN ('117hr1', '116hr1')
GROUP BY bctn, crs_report_bills.bill_id, crs_report_bills.crsreport_id
) crsbillJoin
ON crs_report.id=crsbillJoin.crsreport_id
WHERE bctn IS NOT NULL
GROUP BY bctn, crs_report.id, crsbillJoin.crsreport_id) bctnAgg
GROUP BY bctnAgg.crsid, bctnAgg.crsfile, bctnAgg.crstitle, bctnAgg.crsmetaurl
;
```
![image](https://user-images.githubusercontent.com/217356/121787821-4db52600-cb7d-11eb-9928-6eb9413e748f.png)

**Comment by aih** [comment]
Without deduplication, this is what a bill CRS context section would look like: all of the combined CRS reports, with no way of telling which report is associated with which bill:

![image](https://user-images.githubusercontent.com/217356/122959792-fad72d80-d337-11eb-82e7-867975ace0de.png)

**Comment by aih** [comment]
This is the one report directly associated with this bill:
![image](https://user-images.githubusercontent.com/217356/122960476-4be72180-d338-11eb-841e-9ee28600efbe.png)

**Comment by aih** [comment]
This appears to be working:
![image](https://user-images.githubusercontent.com/217356/124197464-6c735200-da83-11eb-97dc-fbe1779763b8.png)
