### ISSUE TITLE
Bills Related to section- some of the related bills do not link out and Details button does not exist 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#442]
<img width="1048" alt="Screen Shot 2021-06-14 at 11 58 53 AM" src="https://user-images.githubusercontent.com/69855502/121923872-59355800-cd09-11eb-8991-ce8cf558345b.png">

**Comment by aih** [comment]
The only items with 'Details' are ones that have section similarity matches. We may want to explain that in some way.

@ayeshamk, we can add the links (e.g. here 'H. R. 2055 (117th')), but may have to handle it differently from the other ones which are found in the similarity JSON (i.e. they have section similarity)

**Comment by nkinaba** [comment]
I reversed the search for some of the related bills without the details button for HR 736 (116th) and on those bill pages they are picking up that the bills have section matches to HR 736 (116th)


<img width="1293" alt="Screen Shot 2021-06-16 at 12 15 36 PM" src="https://user-images.githubusercontent.com/69855502/122257332-ed382880-ce9d-11eb-8074-13c49beb9cca.png">
<img width="1262" alt="Screen Shot 2021-06-16 at 12 17 21 PM" src="https://user-images.githubusercontent.com/69855502/122257333-ed382880-ce9d-11eb-8aad-3471afa58998.png">
<img width="1246" alt="Screen Shot 2021-06-16 at 12 14 52 PM" src="https://user-images.githubusercontent.com/69855502/122257334-ed382880-ce9d-11eb-8888-3e1f95d91702.png">
<img width="1260" alt="Screen Shot 2021-06-16 at 12 15 12 PM" src="https://user-images.githubusercontent.com/69855502/122257335-edd0bf00-ce9d-11eb-96c8-b89983a8a43d.png">

**Comment by aih** [comment]
This has been fixed and deployed.
