### ISSUE TITLE
Prognosis section in Overview container

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#443]
Missing "Prognosis" data in Overview container.
Govtrack has this information

<img width="564" alt="Screen Shot 2021-06-14 at 12 16 55 PM" src="https://user-images.githubusercontent.com/69855502/121925030-7d456900-cd0a-11eb-8569-95cc6bc720f0.png">

<img width="1276" alt="Screen Shot 2021-06-14 at 12 14 24 PM" src="https://user-images.githubusercontent.com/69855502/121925288-c4cbf500-cd0a-11eb-8594-e15f53b9e667.png">

**Comment by aih** [comment]
Removed the 'Prognosis' section in the UI. That is a formula that govtrack developed and it is out of scope for this project to reproduce.
Closing.
