### ISSUE TITLE
Change "About Us" text from Flatgov to Billmap

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#445]
Change all occurrences of Flatgov to Billmap on the "About Us" landing page 

<img width="1137" alt="Screen Shot 2021-06-15 at 11 49 10 AM" src="https://user-images.githubusercontent.com/69855502/122084762-1d18fa80-cdd0-11eb-8983-a6547aee4b66.png">

**Comment by aih** [comment]
This has been updated by editing the About Us through the Admin panel.
