### ISSUE TITLE
Copy to Clipboard and Export to CSV for "Sponsors of Related Measures"

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#446]
Include Copy to Clipboard and Export to CSV for Bills Related to and Sponsors of Related Measures sections 

<img width="1308" alt="Screen Shot 2021-06-15 at 12 24 48 PM" src="https://user-images.githubusercontent.com/69855502/122089488-cfeb5780-cdd4-11eb-8df1-532019bc1add.png">

<img width="1281" alt="Screen Shot 2021-06-15 at 12 24 55 PM" src="https://user-images.githubusercontent.com/69855502/122089494-d11c8480-cdd4-11eb-9c8a-b1074adb57ce.png">

**Comment by aih** [comment]
This has now been fixed for Bills Related to (see #449).

This issue is the same as #451

**Comment by aih** [comment]
Fixed with #451
