### ISSUE TITLE
Change "Related Bills" title in the Overview section to "Related Bills from the same Congress"

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#470]
<img width="517" alt="Screen Shot 2021-07-01 at 10 37 14 AM" src="https://user-images.githubusercontent.com/69855502/124143135-dd514480-da58-11eb-8d9f-bf023907163b.png">

**Comment by aih** [comment]
The UI currently shows related bills from the *same* congress, not the current congress. This is also what we do in the first tab of the Related bills section below.

**Comment by ayeshamk** [comment]
@nkinaba Should we change it "Related Bills from the same Congress" instead of "Related Bills from this Congress" to avoid ambiguity? The UI shows related bills from the same congress, not the current congress.

**Comment by DanielSchuman** [comment]
Yes, changing it to related bills from the same congress would be idea.
Thank you.
