### ISSUE TITLE
The weekly calendar should begin on Monday instead of Sunday

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#59]

**Comment by smplater** [comment]
![Image 2020-12-15 at 11 20 43 AM](https://user-images.githubusercontent.com/60105995/102242200-cf2a4500-3ec7-11eb-8ef3-e5dc49070740.png)

**Comment by aih** [comment]
This was closed by 786224c and has been deployed.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/103310470-92347700-49cc-11eb-9dc8-fa7c64b82fdd.png)
