### ISSUE TITLE
Tables should allow resizing of columns

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#65]
The new styling of the tables has a search feature (good). But a few things have changed that we want back: columns should be resizeable, especially the Title and other columns that may be cut off.

**Comment by aih** [comment]
![image](https://user-images.githubusercontent.com/217356/100378305-b36a0800-2fc7-11eb-9cf8-da3050f8c342.png)

**Comment by kapphire** [comment]
The issue is resolved.

**Comment by aih** [comment]
Resizing doesn't work right in b786f. The header is resized much more than the columns:

![image](https://user-images.githubusercontent.com/217356/102111237-f8c16e80-3dea-11eb-9a5b-b43d1fa65c4f.png)

**Comment by aih** [comment]
Reviewing this-- resizing *does* work, but is awkward. The user must resize the column heading, and then click the heading again and the full column resizes. 
Closing for now; can enhance in the future.
