### ISSUE TITLE
Scrape Trump Statement of Administration Policy before change in administration 

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#82]
https://www.whitehouse.gov/omb/statements-of-administration-policy/

![Image+2021-01-07+at+3 40 55+PM](https://user-images.githubusercontent.com/60105995/103942880-17233d00-50ff-11eb-88be-c7d5f76466dc.png)

**Comment by aih** [comment]
May want to install scrapy as a project dependency  (https://scrapy.org/), and add the SOA scraper as a task, storing the statement (pdf) along with the link text, which includes the number of the bill.

**Comment by aih** [comment]
I have downloaded these and committed the pdfs in `https://github.com/aih/FlatGov/tree/issue/82-statements-admin-policy`. I also scraped much of the whole whitehouse website with wget, before being blocked by 403 (forbidden) errors.

**Comment by aih** [comment]
This was merged in #130
