### ISSUE TITLE
Change search UI on Home Page

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#83]
![Image 2020-12-15 at 12 45 56 PM](https://user-images.githubusercontent.com/60105995/102252211-ce97ab80-3ed3-11eb-981d-2c8ce52b0004.png)

Search UI should look like the picture above.

**Comment by leedavidr** [comment]
@aih Hi Ari, do our services support this type of search? for congress dropdown
@smplater Are we planning to use the same type of dropdown or have a search results page? If dropdown, I think I may be able to use existing functionality

**Comment by aih** [comment]
The dropdown is supported only insofar as we can filter bills by congress number in the typeahead.
The text similarity search doesn't lend itself to this kind of dropdown. The similarity page has many ways of sorting and filtering by congress

**Comment by aih** [comment]
Deployed on production.
![image](https://user-images.githubusercontent.com/217356/103014008-f2ba4480-44f2-11eb-816f-c5a5c479a42f.png)
