### ISSUE TITLE
Add "Compare" text button under the "Compare Bill Text" column. 

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#89]
![Image+2020-12-21+at+1 22 19+PM](https://user-images.githubusercontent.com/60105995/102809231-a0144780-438f-11eb-89ca-05e32222e374.png)

Compare Text on GovTrack
https://www.govtrack.us/congress/bills/116/hr5430

Compare Text on GovTrack
![Image+2020-12-21+at+2 02 12+PM](https://user-images.githubusercontent.com/60105995/102812555-326b1a00-4395-11eb-8f15-8595607cef28.png)

**Comment by aih** [comment]
Not clear that a `compare` function is in scope. This is supported already on Govtrack. Closing, pending more discussion.
