### ISSUE TITLE
Change section title to Bills Related to [Bill Number]

### ISSUE THREAD

**Issue by smplater** [aih/FlatGov#92]
![Image+2020-12-21+at+1 22 19+PM](https://user-images.githubusercontent.com/60105995/102813253-7f032500-4396-11eb-8817-f3d0e6bbcb5b.png)

**Comment by aih** [comment]
This has been implemented:
![image](https://user-images.githubusercontent.com/217356/112564711-fb901000-8d98-11eb-9578-3f3a421a45c4.png)
