### ISSUE TITLE
Understand the Context - Statement of Administration Policy (SOA)

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#97]
<img width="1201" alt="Screen Shot 2020-12-21 at 2 29 27 PM" src="https://user-images.githubusercontent.com/69855502/102814832-46187f80-4399-11eb-9df2-036baf5265fd.png">

The list of bills in this section are related bills that have a Statement of Administration Policy. 
The "Full Report" button should open up to a PDF of the Statement of Administration Policy for that bill.

**Comment by aih** [comment]
Related to #82

**Comment by aih** [comment]
@ayeshamalika, use the data in https://github.com/aih/FlatGov/tree/main/scrapers/statementAdminPolicy/statementAdminPolicy/pdf (including the metadata in `pdf/meta.json`) to create this table.

This data should be associated with the Bills model and added to the database, then it becomes accessible in creating the SOA tab of the Context tables.

**Comment by ayeshamk** [comment]
Completed and pushed in FT_Branch_1
